### ISSUE TITLE
Re-logging at start of game removes team

### ISSUE THREAD

**Issue by jvpoppel** [Extremelyd1/minecraft-bingo#11]
Just happened in playtest with @Extremelyd1, I relogged at the start of the game and lost my team.

POSSIBLE SOLUTIONS:
- Check teams of players periodically to ensure they are added to the assigned team every (i.e.) 1 minute
- Add command for OP / players with permission to add a player to a team during the game.

**Comment by Extremelyd1** [comment]
Probably fixed in 15085fdfd63cc3ff73f5b074c1cc0f9a39b55ced, I will reopen if otherwise.
