### ISSUE TITLE
Show currently winning team in non-full-card matches

### ISSUE THREAD

**Issue by SquarePlayn** [Extremelyd1/minecraft-bingo#33]
## Feature suggestion:
When a game's win condition is to achieve X rows, also display which team is currently winning.

**Comment by Extremelyd1** [comment]
How would you propose to do this?
Is the winning team defined as the team with the most items?
Or with the most progress towards X lines completed? And if so, how is progress defined exactly.
I was thinking about this, but I can't seem to find a clear way to define "winning" or "progress", which is also easily visualized on the scoreboard on the right of player's screens.

**Comment by SquarePlayn** [comment]
How I envisioned this is that it basically displays the team that would win if the game were to end now (as in, time running out). 

As far as I know, that means the team with the most rows, or if there are multiple, then the team with the most items, or if there are multiple still, then Tie. 

For games where the time limit is infinite, this makes less sense tho indeed. Perhaps then you could just display the team with the most rows completed, and otherwise Tie. If you're playing a game with just 1 row or other kind where displaying it doesn't make much sense, then they can disable it anyways.
