### ISSUE TITLE
Allow restricting bingo to a single world

### ISSUE THREAD

**Issue by CasHsmn** [Extremelyd1/minecraft-bingo#39]
First of all, love the plugin, looks and works much nicer than other ones out there I found.

However, I have one request, as the plugin is difficult to use on a server with multiple worlds. I would love the possibility to enable/disable the plugin through a command or restrict it to a certain world. When the plugin is running I am not able to do anything in my other worlds which is quite inconvenient.

Great plugin but this feature would really seal the deal for me!

**Comment by Extremelyd1** [comment]
This seems like a rather specific use case to me. Could you perhaps explain a bit more in-depth what your setup is? 
From what I understand you have a single server with multiple worlds, of which you want one of them to run this plugin as a minigame.
However, if you want to run minecraft bingo persistent (and/or multiple times), you might want to look into using BungeeCord for this. This allows you to setup a system to launch a separate server running this plugin which can be accessed from the rest of your network (servers).

**Comment by CasHsmn** [comment]
We just have a server with friends in which we use multiverse to have various worlds, it's only small so using bungeecord is a bit overkill.

So for example we may be playing vanilla but then want to do a little bit of bingo. It would be easiest if we could just tp to a world where bingo is ready for us. Or if we run a small minigames event for friends we can easily switch between minigames by having different worlds for each game without affecting the other worlds. 

I just thought I would suggest it as it would make our usage of the plugin easier, and perhaps that of others too. Right now we will add the plugin when we need it, reload the server, play bingo, remove the plugin and reload again. 

Of course it is no problem if it won't be implemented, I still appreciate the plugin! I also have no idea how difficult it would be to make it only work in one world.

Thanks for the reply!

**Comment by Extremelyd1** [comment]
Unfortunately, I don't think that this fits in this project, the scope is a bit too specific for it.
