### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by ASHLEYakaASHLEY** [Extremelyd1/minecraft-bingo#41]
Hi there. Is there a list of permissions for this plugin? Also, I am hoping to find out if there are per world permissions.

**Comment by ASHLEYakaASHLEY** [comment]
Also, is there a reason all commands are disabled once the game has started (even for admin/ops)?

**Comment by Extremelyd1** [comment]
> Hi there. Is there a list of permissions for this plugin? Also, I am hoping to find out if there are per world permissions.

I don't have a permission system set up, all commands are either OP only or public.

> Also, is there a reason all commands are disabled once the game has started (even for admin/ops)?

What exactly do you mean by this? Some commands should be enabled once the game has started, for example `/end`, but also `/card`.

**Comment by ASHLEYakaASHLEY** [comment]
> > Hi there. Is there a list of permissions for this plugin? Also, I am hoping to find out if there are per world permissions.
> 
> I don't have a permission system set up, all commands are either OP only or public.
> 
> > Also, is there a reason all commands are disabled once the game has started (even for admin/ops)?
> 
> What exactly do you mean by this? Some commands should be enabled once the game has started, for example `/end`, but also `/card`.

Unfortunately, typing /end /card, etc says the command is disabled once i start the game. I just discovered this appears to be due to the way it is "preparing team spawns" for bingo. It is moving me players of the world we are in and placing us back in the default world. Is there a way to change which world it prepares team spawns in?

**Comment by ASHLEYakaASHLEY** [comment]
Actually, nevermind, I'm going to bungeecord it. 

I am utilizing luckperms to add some layers of permissions outside of Operator/Player. Is there any plan to add permissions later?
