### ISSUE TITLE
[MinecraftBingo 1.3.3] The plugin won't launch in the server, running Paper 1.16.4

### ISSUE THREAD

**Issue by SnoopTheMiner** [Extremelyd1/minecraft-bingo#42]
Hello! I created a new 1.16.4 world and launched it with Paper 1.16.4 using my host (Pebblehost). I have a handful of other plugins, but this one showed in the console that it didn't launch. Most notably from the console output, it seems that there could be a version mismatch.

```
04.03 16:57:08 [Server] INFO [MinecraftBingo] Enabling MinecraftBingo v1.3.2
04.03 16:57:08 [Server] INFO [MinecraftBingo] Creating Game instance
04.03 16:57:09 [Server] ERROR [MinecraftBingo] Could not start plugin
04.03 16:57:09 [Server] INFO [MinecraftBingo] Disabling MinecraftBingo v1.3.2
```

The above block was all that showed up for the plugin, but the interesting part is that I followed the installation instructions and installed the plugin's 1.3.3 jar, so I'm a bit unsure of why it shows up as v1.3.2 in the console.

Thank you; let me know if I can help at all!

**Comment by SnoopTheMiner** [comment]
A small update: I've tried to use 1.3.2 on paper 1.16.1 while disabling all of the other plugins, and that showed the same error. I also tried to use Maven to package the newest build on github, and that did not work either. I did notice a couple of weird issues when trying to build with the dependencies (in pom.xml, it's saying that bukkit version 1.16.4-R0.1-SNAPSHOT is a dependency, but [bukkit 1.16.x doesn't exist](https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/bukkit/bukkit/)). Is there a way for me to see more detail on what exactly is going wrong upon startup?

**Comment by Extremelyd1** [comment]
The version mismatch is probably an error on my part. Forgetting to update the version in the Maven pom and not in the plugin code or vice versa.

I have now updated the latest release to a version including the latest changes, which includes a fix to display the correct error message when the plugin doesn't start. Please try again and let me know if you still run into problems you can't seem to solve.

As a side note, the dependency of bukkit you are talking about is CraftBukkit. Unfortunately, you need to build this dependency locally yourself with BuildTools (more information [here](https://www.spigotmc.org/wiki/buildtools/#compile-craftbukkit).

**Comment by SnoopTheMiner** [comment]
Hello! Apologies for the late response, but using the new version I was able to get it working from the error messages; thank you!

The main issue was my world name; the plugin requires the world to be named "world" so that's where I was going wrong. 

I'm a bit curious; how do the generate/worlds commands work? Are you able to switch between the worlds or do you need to restart the server and rename the loaded world to "world" each time you pregen one and want to load it?

**Comment by Extremelyd1** [comment]
> I'm a bit curious; how do the generate/worlds commands work? Are you able to switch between the worlds or do you need to restart the server and rename the loaded world to "world" each time you pregen one and want to load it?

Unfortunately yes, you need to rename the world you want to use to "world". The advantage of the pregeneration commands is that you can generate a lot of worlds in advance and then use them later.

I'm closing this issue since it seems resolved, if you have any more issues/questions, please open a different one.
