### ISSUE TITLE
Questions.

### ISSUE THREAD

**Issue by ASHLEYakaASHLEY** [Extremelyd1/minecraft-bingo#43]
> I'd like to build out the spawn area to have some instructions while my gamers wait. Is there a way to make it let me interact with the world?

> Also, is there a way to automate joining teams? Like a gui interface for players to select their own team so that an Operator does not have to be online to manually assign teams. 

> Also, I'm not sure why but even though I was able to start a game, it would not let me /end it.

**Comment by ASHLEYakaASHLEY** [comment]
I fixed the /end not working. Bungee has a /end command which although was disabled via perms, had to be fully disabled. 

The first two requests/questions though I have not determined a way to work around though.
-  Is there a way to make it let me interact with the world pre-game so that I can build out a spawn area?
-  is there a way to automate joining teams? Like a gui interface for players to select their own team so that an Operator does not have to be online to manually assign teams.

Two more questions, 
- how do you restart the game once one has ended? I've tried having players leave the lobby and return, but it does not appear to do anything.
-  how do you add someone to the spectator /team ?

**Comment by SnoopTheMiner** [comment]
> * how do you restart the game once one has ended? I've tried having players leave the lobby and return, but it does not appear to do anything.

Hi! I found the fix to this to just be to restart the server. It should work after that!

I haven't tested the latter, but I believe someone that joins when the game is in session will automatically be a spectator (this could be wrong, though).

**Comment by Extremelyd1** [comment]
> how do you restart the game once one has ended? I've tried having players leave the lobby and return, but it does not appear to do anything.

You would have to restart the server and generate a new world if you want to restart the game.

> how do you add someone to the spectator /team ?

Anyone not added to a team is considered a spectator. This means that if you `/team remove <player name>` it will "add" them to the spectator team.

I'm closing this issue now, if you have any more concerns or issues, please open another issue.

**Comment by ASHLEYakaASHLEY** [comment]
> > how do you restart the game once one has ended? I've tried having players leave the lobby and return, but it does not appear to do anything.
> 
> You would have to restart the server and generate a new world if you want to restart the game.
> 
> > how do you add someone to the spectator /team ?
> 
> Anyone not added to a team is considered a spectator. This means that if you `/team remove <player name>` it will "add" them to the spectator team.
> 
> I'm closing this issue now, if you have any more concerns or issues, please open another issue.

Hey, can you take a look at the first two questions?

> Is there a way to make it let me interact with the world pre-game so that I can build out a spawn area?

> is there a way to automate joining teams? Like a gui interface for players to select their own team so that an Operator does not have to be online to manually assign teams.
