### ISSUE TITLE
Schematic Spawn

### ISSUE THREAD

**Issue by ASHLEYakaASHLEY** [Extremelyd1/minecraft-bingo#45]
Is there a way for me to add a schematic to the spawn area? I've seen this done for other gamemode plugins like hunger games as an area that houses players, gives them the rules of the game, has command blocks or something with a clickable command to let them automate teams.

**Comment by Extremelyd1** [comment]
This is not natively supported. The spawn is dynamically chosen by the plugin since it is the center of the border that always includes a stronghold in the overworld. So it would be quite difficult to add something to the spawn.
