### ISSUE TITLE
Nether Portals blocked by world border

### ISSUE THREAD

**Issue by joeShuff** [Extremelyd1/minecraft-bingo#46]
Hi!
I'd like to start off by saying thank you for the plugin, me and some friends have played it quite a bit recently and we've thoroughly enjoyed it, so thank you!

Now we noticed an issue that caused us to stop playing and worry about it being impossible to complete the bingo. When a player tried to go to the nether, they weren't being teleported through the portal. I hopped into creative and tried a portal at the center of the world and it was also not teleporting me. Initially we set the world size to 1500 and nether size to 1000 blocks.

I went into the nether by doing
`/execute in world_the_nether run teleport @s 0 130 0`
and then I checked the world border that was 1000 blocks wide before setting the border to 100000 width and portals then worked as expected.

I am not quite sure how world border limits work when crossed over from the overworld to the nether. I have made a UHC plugin that centers the world borders around 0,0 and makes them the same size in the nether/overworld and I have never seen behaviour like this.

If you need any more info let me know.

**Comment by Extremelyd1** [comment]
If you could provide me with a world seed that causes this issue that would be great!

I could imagine this issue occurring since the plugin overrides the default portal generation behaviour of vanilla minecraft. This is needed because the borders in both dimensions are not centered on the same point. The borders are determined to always include a stronghold in the overworld and a nether fortress in the nether.

**Comment by joeShuff** [comment]
I played a game the other day and experienced it so I will test again with the same seed and config then I will provide it for you to test too :)

**Comment by Extremelyd1** [comment]
> I played a game the other day and experienced it so I will test again with the same seed and config then I will provide it for you to test too :)

I (supposedly) fixed this issue in the latest release; I'm not sure if you mean that still came across it with the latest version, but if that is the case, then I will reopen this issue and would greatly appreciate the seed and config!

**Comment by joeShuff** [comment]
I tested a world on both 1.3.4 and 1.3.5 and can confirm that (for this world) the issue has been solved!

I will keep my eye out for it whilst playing in the latest version and reopen this if I see it again!

Thanks for solving!
