### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by Extremelyd1** [Extremelyd1/minecraft-bingo#52]
Minecraft release notes can be found [here](https://minecraft.fandom.com/wiki/Java_Edition_1.17).
Spigot developer notes can be found [here](https://www.spigotmc.org/threads/spigot-bungeecord-1-17.510208/).

Notable changes:
- World generation may have changed due to experimental features that allow new cave biomes. These experimental generation features will probably not be supported until the 1.18 release, so this is only relevant for world pre-generation and structure locating features in the plugin.
- A plethora of blocks and items have been added; these need to be given a tier by determining how obtainable they are.
- The texture of copper related items might change over time, thus one of variants needs to be picked for the bingo card.
- The texture of some existing blocks/items has changed, these include but might not be limited to:
  - Blackstone variants, ores, pumpkin, signs, smoker, clock, compass, jungle door, and sugar cane.

**Comment by JayJay1989** [comment]
Could you add a setting for sleep percentage?

class: PlayerJoinLeaveListener
```java
    @EventHandler
    public void onPlayerJoin(PlayerJoinEvent e) {

        this.game.onPregameUpdate(Bukkit.getOnlinePlayers().size());

        Player player = e.getPlayer();

        if (game.getState().equals(Game.State.PRE_GAME)) {
            -->player.getWorld().setGameRuleValue("playersSleepingPercentage", game.getConfig().getSleepPercentage());
```

class: Config

```java
    /**
     * The percentage of players needed to sleep
     */
    private int sleepPercentage;

    public Config(JavaPlugin plugin) throws IllegalArgumentException {
        ...
        sleepPercentage = config.getInt("sleep-percentage");
        ...
    }

    public String getSleepPercentage() {
        return String.valueOf(sleepPercentage);
    }
```

**Comment by Extremelyd1** [comment]
@JayJay1989 although your comment pertains to a feature that was introduced in 1.17, I feel that it is still out of place in this issue. You can make a new issue with the label "enhancement" if still want to have this added.

On a separate note: you seem to have provided all the code necessary to get this working, so you can simply fork the repository and make a PR with the proposed changes.

**Comment by JayJay1989** [comment]
Well, you need to run the command every time you setup a world. So this isn't out of place. Why do it manual of it can be done with a simple config

**Comment by JayJay1989** [comment]
Will do some pull request for some of the features i implemented yesterday
