### ISSUE TITLE
some files for installization are missing

### ISSUE THREAD

**Issue by H-J-Granger** [Extremelyd1/minecraft-bingo#59]
README.md mentions, 

>  Move the .txt files and the images/images.zip in the item_data folder to <server>/plugins/MinecraftBingo/item_data. Then unzip the images/images.zip archive.

but it doesn't seem to give any download url of any `.txt` files or `images.zip`.

I downloaded the jar file from the release and move it into my `plugins` directory, but when I run my server I only found a `config.yml` in `plugins/MinecraftBingo`. Could anyone help me?

**Comment by Extremelyd1** [comment]
That's my bad, while the `.jar` file updated in the last few releases, the `item_data.zip` did not, so I forgot to include it in the release. I have rectified this now, you should see a `item_data.zip` in the [latest release](https://github.com/Extremelyd1/minecraft-bingo/releases/tag/v1.6.0), which are the files you are missing.
