### ISSUE TITLE
Change TeamCommand check to allow it in post-game ?

### ISSUE THREAD

**Issue by JPenuchot** [Extremelyd1/minecraft-bingo#62]
Here's the line: 
https://github.com/Extremelyd1/minecraft-bingo/blob/c3d9abd0dc6563da5c7c65d93dea01beddb4ba1f/src/main/java/com/extremelyd1/command/TeamCommand.java#L42

Is there a reason to not put `if (game.getState().equals(Game.State.IN_GAME))` instead?

I've tried doing it and it doesn't seem to mess with the plugin, but I'd like to have your feedback on that.

**Comment by JPenuchot** [comment]
Also 2nd question (although a bit off-topic): is there a reason to have a post-game state instead of just going back to pre-game ?

**Comment by Extremelyd1** [comment]
The post-game state is for exploring the world after the game is finished, which includes checking chests that one might have come across if the game had not yet ended (although this is an active issue #38).
The difference between post-game and pre-game is thus that we explicitly do not want players exploring in the pre-game (to avoid spoilers/world information).
