### ISSUE TITLE
Some classes are missing

### ISSUE THREAD

**Issue by escargoog** [Extremelyd1/minecraft-bingo#66]
Hi, 
While trying to tweak a custom version for your bingo (which I adore btw!) I encountered some problems.
Some classes are missing (LevelChunk and BoundingBox in WorldManager.java, as well as ChatFormatting and DisplayInfo in ChatListener.java, and AreaEffectCloud and EnderDragon in ItemListener.java).
I tried to generate both Spigot and Bukkit jars with the latest BuildTools version, and I set up all the dependencies on a local file on my computer. 
Did I do something wrong? 
Thanks in advance, have a nice day! 
escargoog

**Comment by Extremelyd1** [comment]
Try to look at the `pom.xml` file in the root of the project, that should give you an indication of what you are missing. I'm guessing that you are missing the craftbukkit requirement, which can be compiled via BuildTools with `java -jar BuildTools.jar --rev 1.18.1 --compile craftbukkit`.

**Comment by JPenuchot** [comment]
Hello,

The new `pom.xml` expects the remapped versions of Spigot and CraftBukkit that are not built by default. You need to run `java -jar BuildTools.jar --rev 1.18.1 --compile craftbukkit --remapped` and `java -jar BuildTools.jar --rev 1.18.1 --remapped` to get the proper JAR files.

Regards,
Jules

**Comment by escargoog** [comment]
Hello!
Thanks for the advice! There were some previous dependencies that overlapped the remapped and shaded ones and it clashed in the code. I manually deleted those dependencies and now everything works!

Thanks again and have a nice day/night.
escargoog
