### ISSUE TITLE
Support for Minecraft 1.18.2

### ISSUE THREAD

**Issue by Kroko-fant** [Extremelyd1/minecraft-bingo#67]
Hi, as a quick note Paper 1.18.2 servers will not work with the 1.18.1 version of the plugin :|
![grafik](https://user-images.githubusercontent.com/25010075/165918969-afa90850-a6b4-42c9-944b-c9021d8a03cf.png)
I think its more of a minor issue that can probably be resolved pretty fast however I'm sadly not a minecraft dev.

**Comment by Kroko-fant** [comment]
Note: The description is also referring to version 1.16.5 while the version in the release tab is 1.18.1

**Comment by Extremelyd1** [comment]
The latest version now supports MC 1.19, additionally the readme has been updated.
