### ISSUE TITLE
Items from Bingo map UI can be moved to player's inventory

### ISSUE THREAD

**Issue by henrikx** [Extremelyd1/minecraft-bingo#69]
The bingo map UI lets you drag items from the bingo card to the inventory of the player. This bug is game breaking cause now everyone can get the requested item just from using that menu.

**Comment by henrikx** [comment]
![image](https://user-images.githubusercontent.com/10342989/192106995-18bf7f85-4cb5-4e1f-a49a-9a1fc4f5fa9e.png)

Server is Paper 1.19

**Comment by Extremelyd1** [comment]
Are you able to consistently reproduce this issue? If so, could you please give the steps on how to do this?
I'm not able to move any items from the Bingo map UI to the player's inventory with any sort of click on Paper 1.19.

**Comment by henrikx** [comment]
> Are you able to consistently reproduce this issue? If so, could you please give the steps on how to do this? I'm not able to move any items from the Bingo map UI to the player's inventory with any sort of click on Paper 1.19.

There was nothing special about the server. Just a few plugins and fresh world. It really shouldn't matter, but I'm noting it just in case that players connect via Velocity proxy.

For me, the bug was consistent across multiple server restarts. No errors in the console either.

```
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
```
```
Plugins: Essentials, EssentialsSpawn, LuckPerms, TrackingCompass, WorldEdit, WorldGuard
```

Other than that, please let me know any specific information which could help you reproduce it.

**Comment by Extremelyd1** [comment]
> ```
> Plugins: Essentials, EssentialsSpawn, LuckPerms, TrackingCompass, WorldEdit, WorldGuard
> ```

Could you try running it without any of the extra plugins and see if that changes anything?

**Comment by Extremelyd1** [comment]
Can't reproduce
